product template
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Swapit pull request #14
Opened 2024-07-03 13:35 UTC by Airyoldi

2024-07-03 13:48 UTC, Ludovicscelles approved these changes

2024-07-03 14:02 UTC, Alexandre78R requested changes

2024-07-03 14:02 UTC, Alexandre78R commented on client/src/components/swapProposition/swapProposition.css
> +.proposition {
English name class

2024-07-03 14:02 UTC, Alexandre78R commented on client/src/components/swapProposition/swapProposition.css
> +.PropositionProducts {
rename camel case and proposition english

2024-07-03 14:02 UTC, Alexandre78R commented on client/src/components/swapProposition/swapProposition.css
> +  .proposition {
rename in english

2024-07-03 14:02 UTC, Alexandre78R commented on client/src/components/swapProposition/swapProposition.css
> +  .PropositionProducts {
rename camel case and proposition english

2024-07-03 14:02 UTC, Alexandre78R commented on client/src/components/swapProposition/swapProposition.css
> +  .PropositionProducts {
rename camel case and proposition english

2024-07-03 14:02 UTC, Alexandre78R commented on client/src/components/swapProposition/swapProposition.css
Re check all class name please :)

2024-07-03 14:02 UTC, Alexandre78R commented on client/src/components/swapProposition/swapProposition.jsx
Rename folder and file SwapPropisition

2024-07-03 14:02 UTC, Alexandre78R commented on client/src/pages/Product/ProductPage.css
Rename file productPage

2024-07-03 14:02 UTC, Alexandre78R commented on client/src/pages/Product/ProductPage.jsx
> +  console.log(product);
delete console. log and delete rules // eslint-disable-next-line no-console

2024-07-03 14:02 UTC, Alexandre78R commented on client/src/pages/Product/ProductPage.css
> +h4 {
Add className

2024-07-03 14:02 UTC, Alexandre78R commented on client/src/pages/Product/ProductPage.css
> +h2 {
Add className

2024-07-03 14:02 UTC, Alexandre78R commented on client/src/pages/Product/ProductPage.css
> +  h4 {
Add className

2024-07-04 10:14 UTC, Alexandre78R requested changes

2024-07-04 10:14 UTC, Alexandre78R commented on client/src/pages/Product/productPage.css
> +  h4 {
replace name class please

2024-07-04 12:48 UTC, Alexandre78R requested changes

2024-07-04 12:48 UTC, Alexandre78R commented on client/src/components/SwapProposition/swapProposition.css
> +h3 {
add classname

2024-07-04 12:48 UTC, Alexandre78R commented on client/src/components/SwapProposition/swapProposition.css
> +  h3 {
add classname

2024-07-04 13:04 UTC, Alexandre78R approved these changes

2024-07-04 13:05 UTC, merged