Profile desktop team checking please
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Swapit pull request #23
Opened 2024-07-10 15:13 UTC by JyAjAn

2024-07-10 15:20 UTC, JyAjAn commented
modification made thx ( TA )

2024-07-11 09:58 UTC, NicosMQ approved these changes

2024-07-11 10:14 UTC, VinchC requested changes

2024-07-11 10:14 UTC, VinchC commented on client/src/Router.jsx
> +        path: "/profile/:name/:id",
choose :id or :name, not both

2024-07-11 10:14 UTC, VinchC commented on client/src/pages/Profile/Profile.css
> +  .Larger {
larger

2024-07-11 10:14 UTC, VinchC commented on client/src/pages/Profile/Profile.css
> +  .Larger {
cf. supra

2024-07-11 10:14 UTC, VinchC commented on client/src/pages/Profile/Profile.css
> +.Five-Rate-Active {
camelCase

2024-07-11 10:14 UTC, VinchC commented on client/src/pages/Profile/Profile.css
> +.Larger {
cf. supra

2024-07-11 10:14 UTC, VinchC commented on client/src/pages/Profile/Profile.css
> +  #ButtonStar {
camelCase

2024-07-11 10:14 UTC, VinchC commented on client/src/pages/Profile/Profile.css
> +  #ButtonStar {
camelCase

2024-07-11 10:14 UTC, VinchC commented on client/src/pages/Profile/Profile.css
> +.Cate-value-empty::before {
camelCase

2024-07-11 10:14 UTC, VinchC commented on client/src/pages/Profile/Profile.css
> +#ButtonStar {
camelCase

2024-07-11 10:14 UTC, VinchC commented on client/src/pages/Profile/Profile.css
> +.Custom-button:hover {
camelCase

2024-07-11 10:14 UTC, VinchC commented on client/src/pages/Profile/Profile.jsx
> +            <div className="Five-Rate-Active Larger">
camelCase

2024-07-11 12:26 UTC, VinchC approved these changes

2024-07-11 12:26 UTC, merged